SUBMAKE=make -C apps/serial2can 
all:
	$(SUBMAKE) all

clean:
	$(SUBMAKE) clean

load:
	$(SUBMAKE) load

upload:
	$(SUBMAKE) upload

lock:
	$(SUBMAKE) lock

unlock:
	$(SUBMAKE) unlock

reset:
	$(SUBMAKE) reset

debug:
	$(SUBMAKE) debug

openocd:
	$(SUBMAKE) openocd

.PHONY: clean load upload lock unlock reset debug openocd

